[package]
name = "loro"
version = "1.5.9"
edition = "2021"

[lib]
crate-type = ["dylib"]
name = "loro"

[dependencies]
loro-ffi = "1.5.10"

[bindings.csharp]
namespace = "LoroCs"
access_modifier = "public"
