[package]
name = "loro-cs"
version = "1.5.8"
edition = "2021"

[lib]
crate-type = ["dylib"]
name = "loro_cs"

[dependencies]
loro-ffi = "1.5.8"
uniffi = "0.28.3"

[build-dependencies]
uniffi = { version = "0.28.3", features = ["build"] }
